import Dashboard from './Dashboard.js';
const navLabels=[['#home','Главная'],['#charts','Чарты'],['#giveaways','Раздачи'],['#tasks','Задачи']];
document.addEventListener('click',event=>{const link=event.target.closest('a');if(link&&link.getAttribute('href')==='#dota')link.setAttribute('href','#charts');if(link&&link.getAttribute('href')==='#deals')link.setAttribute('href','#giveaways')});
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="styles/soft.css"><link rel="stylesheet" href="styles/light.css"><link rel="stylesheet" href="styles/finish.css"><link rel="stylesheet" href="styles/final2.css"><link rel="stylesheet" href="styles/labels.css">');
const matrix=document.createElement('div');matrix.className='matrix-rain';const glyphs='01{}[]<>/\\+=*#@';for(let i=0;i<22;i++){const col=document.createElement('span');col.className='matrix-column';col.textContent=Array.from({length:28},()=>glyphs[Math.floor(Math.random()*glyphs.length)]).join('\n');col.style.left=`${Math.random()*100}%`;col.style.animationDuration=`${10+Math.random()*14}s`;col.style.animationDelay=`-${Math.random()*15}s`;matrix.append(col)}document.body.append(matrix);
const app=document.querySelector('#app'); const dashboard=new Dashboard(app);document.querySelectorAll('.main-nav a').forEach((a,i)=>{a.href=navLabels[i][0];a.textContent=navLabels[i][1]});
const views={home:()=>`<section class="home-view"><div class="hero-glitch"><span class="hero-kicker">// PLAYER SYSTEM ONLINE</span><h1>PLAY<br><em>THE NOISE</em></h1><p>Персональный игровой центр для тех, кто любит видеть больше, чем просто счет побед.</p><div class="hero-actions"><a class="cta" href="#dota">Открыть статистику <b>↗</b></a><a class="ghost-link" href="#deals">Смотреть скидки <b>↓</b></a></div><div class="hero-lines"><span>01 / SIGNAL</span><span>02 / INPUT</span><span>03 / OUTPUT</span></div></div><div class="home-side"><div class="signal-card"><span class="signal-label">SYSTEM SIGNAL</span><strong>99.8<span>%</span></strong><small>connection stable</small><i></i></div><div class="quote-place"><span>QUOTE OF THE DAY</span><blockquote>«Каждый матч — новая история.»</blockquote><small>— GAMEPULSE / 001</small></div></div></section><section class="home-strip"><span>LIVE API STREAM</span><span class="ticker">DOTA 2 // STEAM DEALS // PERSONAL GOALS // DOTA 2 // STEAM DEALS //</span></section>`,dota:()=>`<section class="page-head"><span class="page-index">01 / API PROFILE</span><h1>DOTA 2<br><em>PLAYER DATA</em></h1><p>Профиль, последние матчи и быстрый срез активности из OpenDota.</p></section><div class="single-widget" id="dota-mount"></div>`,deals:()=>`<section class="page-head"><span class="page-index">02 / MARKET SCAN</span><h1>STEAM<br><em>DEALS</em></h1><p>Поиск и просмотр актуальных предложений с постраничной навигацией.</p></section><div class="single-widget" id="deals-mount"></div>`,tasks:()=>`<section class="page-head"><span class="page-index">03 / PLAYER LOG</span><h1>YOUR<br><em>OBJECTIVES</em></h1><p>Собери личный список игровых целей и отмечай прогресс.</p></section><div class="single-widget" id="tasks-mount"></div>`};
const current=()=>({charts:'dota',giveaways:'deals'}[location.hash.slice(1)]||location.hash.slice(1)||'home');
function render(){const key=current();setTimeout(()=>{app.innerHTML=(views[key]||views.home)();dashboard.clear();if(key==='dota'){const heading=app.querySelector('.page-head h1');const copy=app.querySelector('.page-head p');if(heading)heading.innerHTML='GAME<br><em>ONLINE</em>';if(copy)copy.textContent='Текущий онлайн любой игры по Steam App ID через Steam Web API.';dashboard.mount('dota-mount','dota')}if(key==='deals')dashboard.mount('deals-mount','deals');if(key==='tasks')dashboard.mount('tasks-mount','todo');document.querySelectorAll('.main-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${key}`))},80)}
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const nav=document.querySelector('.main-nav');const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('.main-nav').classList.remove('open')));
const themes=['dark','light'];const savedTheme=localStorage.getItem('gamepulse-theme');document.body.dataset.theme=themes.includes(savedTheme)?savedTheme:'dark';document.querySelector('#theme-switch').addEventListener('click',()=>{const next=document.body.dataset.theme==='dark'?'light':'dark';document.body.dataset.theme=next;localStorage.setItem('gamepulse-theme',next)});window.addEventListener('hashchange',render);render();
